# ============================================================
# Auth Lab Gateway — 认证服务统一入口
# 端口：18090
# ============================================================
server:
  port: 18090

spring:
  application:
    name: security-gateway
  cloud:
    nacos:
      discovery:
        server-addr: @nacos.host@:@nacos.port@
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: session-auth
          uri: lb://security-session
          predicates:
            - Path=/api/session/**
        - id: jwt-auth
          uri: lb://security-jwt-auth-server
          predicates:
            - Path=/api/jwt/**
        - id: opaque-auth
          uri: lb://security-opaque-token
          predicates:
            - Path=/api/opaque/**
        - id: oauth2-auth-server
          uri: lb://security-oauth2-auth-server
          predicates:
            - Path=/api/oauth2-auth/**
        - id: oauth2-resource-server
          uri: lb://security-oauth2-resource-server
          predicates:
            - Path=/api/oauth2-resource/**
        - id: oauth2-client
          uri: lb://security-oauth2-client
          predicates:
            - Path=/api/oauth2-client/**

logging:
  level:
    root: INFO
    com.lab.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
